### ISSUE TITLE
Property 'required' makes form unusable

### ISSUE THREAD

**Issue by martijnvbeek** [jshjohnson/Choices#338]
When a Choice is 'required' but not valid an error is thrown in the console: 

`An invalid form control with name='...' is not focusable.`

The error cancels the form submit event.

Example: https://jsbin.com/xixupew/6

btw. The required property is not inherited from the original tag

**Comment by fernandoagarcia** [comment]
@martijnvbeek  the reason this happens is because the select input is actually hidden and replaced with the choices interface. You will need to do some js validation on submit.

**Comment by martijnvbeek** [comment]
A solution could be to move the name + id + required (and other attributes) from the original select to the input. choices__input

**Comment by fernandoagarcia** [comment]
@martijnvbeek that won't work since that is just a field to search for options. You can probably force it but it wouldn't a very elegant solution. You want to always set the required to the input that holds the true value. You won't be able to use required on hidden elements (display: none;).  Your best option is to use an event listener 'submit' which is common when doing JS validation.

https://output.jsbin.com/cujapaqawe/

**Comment by martijnvbeek** [comment]
This a real game changer for the project I'm working on (and I really like Choices). Client side validation is a luxury that I have disabled at the moment due this limitation of Choices. Currently our +200 forms rely on default browser validation, nothing javascript. Our real validation is done by the server (naturally). 

Strange that browsers submit data from form elements that have `display: none` imho.

**Comment by fernandoagarcia** [comment]
@martijnvbeek sounds like a form builder. But if that's the case stick with the native select input and use CSS to style it differently. Forms will submit data from hidden inputs and any input in the form that has a value. Choices serves a specific objective... to allow a user to quickly search and select a large list of options. That is quite a lot of JS to dedicate to you select inputs in your form builder. Choices is best used as part of a User Interface for application instead of forms. I know technically UI is a giant form in it self but I want to point out that User Forms like contact us or Sign in are more of a basic interaction which should use the basic native inputs interface.

**Comment by philsbury** [comment]
@martijnvbeek @fernandoagarcia Could the select not just be visually hidden?

```css
.choices__input {
  display: block;
  position: absolute;
  width: 0;
  height: 0;
  opacity: 0;
}
```

Might need some `!important`s in there the combat the ones that already exist, but the validator should see it but users won't.

**Comment by tomasmcm** [comment]
@philsbury 's approach is much better than doing JS validation. +1 for using this!
In the meanwhile, you can apply some styles after initialising the Choices object:
```
// el is the element used to create new Choices(elements, {options});
el.style.display = "";
el.style.zIndex = -999;
el.style.opacity = 0;
el.style.position = "absolute";
```

**Comment by renatodeleao** [comment]
Yup I also prefer @martijnvbeek @tomasmcm solutions.
I always have an utility class in my projects for that hides elements, but keeps them for screen-readers.  This will do the trick for required fields.

```scss
@mixin screen-readers-only() {
  border: 0 !important;
  clip: rect(0 0 0 0) !important;
  height: 1px !important;
  margin: -1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}

.u-sr-only { @include screen-readers-only}
```

```javascript
const example = new Choices(element, {
  callbackOnInit: function(){
    this.passedElement.style.display = "block"
    this.passedElement.classList.add('u-sr-only');
    // If You want to disable it from screen readers
    this.passedElement.setAttribute('aria-hidden', true);
  }
});
