### ISSUE TITLE
"display:none" for replaced selects precludes html5 validation

### ISSUE THREAD

**Issue by Shoplifter** [jshjohnson/Choices#416]
setting styles as used in e.g. [`.visuallyhidden`](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L130) would preserve this functionality for choices

UPDATE:
it is possible to overrule this in css:
````css

.#{$choices-selector}__input {
  ...
  &.is-hidden {
    position: absolute;
    display: block !important; /* overrule inline style */
    border: 0 !important;
    clip: rect(1px, 1px, 1px, 1px);
    clip-path: circle(1% at 1% 1%);
    height: 1px;
    overflow: hidden;
    padding: 0;
    bottom: 0;
  }
}
````
this makes browser generated tooltips from html5 validation appear in the right place, though `!important` would be unnecessary when updating js code.
