### ISSUE TITLE
How to remove itemSelectText?

### ISSUE THREAD

**Issue by orgmatileg** [jshjohnson/Choices#421]
![image](https://user-images.githubusercontent.com/25648258/43090784-8ad5d9f2-8ed2-11e8-9b07-db6b5f53e103.png)

My code:

   const choices = new Choices('.ddrakit', {
        placeholder: false,
        itemSelectText: '',
    });

How to remove that red sign, i tried set it into null still not able to remove that ?

I see that itemSelectText create div or something that blocking the text, you can check above..

**Comment by ChrisTalman** [comment]
I'm not aware of a config option for this, but I think it can be done with the following CSS:

```CSS
.choices[data-type*=select-one] > .choices__list > .choices__list > .choices__item--selectable
{
	padding-right: 0px;
}
.choices[data-type*=select-one] > .choices__list > .choices__list > .choices__item--selectable::after
{
	display: none;
}
```

It would be nice for this to be a config option, just to make things more concise with less code.
