### ISSUE TITLE
html5 validation not working with required attribute on <select>

### ISSUE THREAD

**Issue by maximelebreton** [jshjohnson/Choices#449]
Hi there!

Sorry, I have no time to make a pull request,
but here is my quick fix to make it works with a native behaviour (not battle tested, but I think it's clean):

```css
.choices[data-type*="select-one"] select.choices__input {
    display: block !important;
    opacity: 0;
    pointer-events: none;
    position: absolute;
    left: 0;
    bottom: 0;
}
```
