### ISSUE TITLE
[Windows 10][Chrome] Icons don't work 

### ISSUE THREAD

**Issue by LuizMoratelli** [jshjohnson/Choices#593]
Icons, e.g. in selects, don't appear correctly for me. As you can see: http://prntscr.com/nsse0o

I used CSS to fix, something like this:
```CSS
.chosen-container-multi .chosen-choices li.search-choice .search-choice-close {
    // [...]
    background-size: 52px 37px !important;
}
```

After my "CSS fix": http://prntscr.com/nsscfn

Is this just my problem?

Ps.: using a retina screen (MacBook Pro) works correctly.
